import maya.cmds as cmds

cmds.polySphere(radius=5,
                subdivisionsX=18,
                subdivisionsY=10,
                axis=[0,1,0],
                createUVs=2,
                constructionHistory=1)
cmds.move(0,0,0, relative=True)
cmds.polySphere(radius=4,
                subdivisionsX=16,
                subdivisionsY=8,
                axis=[0,1,0],
                createUVs=2,
                constructionHistory=1)
cmds.move(0,6,0, relative=True)
cmds.polySphere(radius=3,
                subdivisionsX=14,
                subdivisionsY=6,
                axis=[0,1,0],
                createUVs=2,
                constructionHistory=1)
cmds.move(0,11,0, relative=True)
cmds.polySphere(radius=1,
                subdivisionsX=5,
                subdivisionsY=5,
                axis=[0,1,0],
                createUVs=2,
                constructionHistory=1)
cmds.move(0,0,5, relative=True)
cmds.polySphere(radius=1,
                subdivisionsX=5,
                subdivisionsY=5,
                axis=[0,1,0],
                createUVs=2,
                constructionHistory=1)
cmds.move(0,6.5,4, relative=True)
cmds.polySphere(radius=.5,
                subdivisionsX=5,
                subdivisionsY=5,
                axis=[0,1,0],
                createUVs=2,
                constructionHistory=1)
cmds.move(1,12,2.5, relative=True)
cmds.polySphere(radius=.5,
                subdivisionsX=5,
                subdivisionsY=5,
                axis=[0,1,0],
                createUVs=2,
                constructionHistory=1)
cmds.move(-1,12,2.5, relative=True)
cmds.polyCone(radius=.5,
                height=2,
                subdivisionsX=20,
                subdivisionsY=1,
                subdivisionsZ=0,
                axis=[0,0,1],
                roundCap=0,
                createUVs=2,
                constructionHistory=1)
cmds.move(0,10.9,3, relative=True)
cmds.polyCylinder(radius=2,
                  height=1,
                  subdivisionsX=16,
                  subdivisionsY=1,
                  subdivisionsZ=1,
                  axis=[0,1,0],
                  roundCap=0,
                  createUVs=3,
                  constructionHistory=1)
cmds.move(0,14,0, relative=True)
cmds.polyCylinder(radius=1.5,
                  height=2,
                  subdivisionsX=7,
                  subdivisionsY=7,
                  subdivisionsZ=7,
                  axis=[0,1,0],
                  roundCap=0,
                  createUVs=3,
                  constructionHistory=1)
cmds.move(0,15,0, relative=True)
cmds.polyCylinder(radius=.5,
                  height=5,
                  subdivisionsX=4,
                  subdivisionsY=1,
                  subdivisionsZ=1,
                  axis=[1,0,0],
                  roundCap=0,
                  createUVs=3,
                  constructionHistory=1)
cmds.move(6,6,0, relative=True)
cmds.polyCylinder(radius=.5,
                  height=5,
                  subdivisionsX=4,
                  subdivisionsY=1,
                  subdivisionsZ=1,
                  axis=[1,0,0],
                  roundCap=0,
                  createUVs=3,
                  constructionHistory=1)
cmds.move(-6,6,0, relative=True)
cmds.polyTorus(radius=1,
                  sectionRadius=0.5,
                  twist=0,
                  subdivisionsX=3,
                  subdivisionsY=3,
                  axis=[1,0,0],
                  createUVs=1,
                  constructionHistory=1)
cmds.move(-4,6.3,0, relative=True)
cmds.polyTorus(radius=1,
                  sectionRadius=0.5,
                  twist=0,
                  subdivisionsX=3,
                  subdivisionsY=3,
                  axis=[1,0,0],
                  createUVs=1,
                  constructionHistory=1)
cmds.move(4,6.3,0, relative=True)
cmds.polyTorus(radius=3,
                  sectionRadius=0.5,
                  twist=0,
                  subdivisionsX=12,
                  subdivisionsY=6,
                  axis=[0,1,0],
                  createUVs=1,
                  constructionHistory=1)
cmds.move(0,9,0, relative=True)
cmds.polyTorus(radius=4,
                  sectionRadius=0.5,
                  twist=0,
                  subdivisionsX=12,
                  subdivisionsY=6,
                  axis=[0,1,0],
                  createUVs=1,
                  constructionHistory=1)
cmds.move(0,4,0, relative=True)